version: 2.0

jobs:
  npm-test:
    docker:
      - image: circleci/node:12.9.0@sha256:2d631878cad440bc598725ce5dec223be0fdd462c666619d034f652efab21831
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-v1-{{ .Branch }}-
            - npm-v1-
          name: Restore npm cache
      - run:
          command: npm ci
          name: Install npm dependencies
      - save_cache:
          key: npm-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          name: Save npm cache
          paths:
            - ~/.npm
      - run:
          command: npm test
          name: Run JavaScript unit tests

workflows:
  version: 2
  lint-test-build:
    jobs:
      - npm-test
